<div class="main-container">
    <!-- nav -->
    <?php new Home_NavPlugin(); ?>
    <!-- /.nav -->
    <!-- content-container -->
    <div class="content-container">
        <!-- Header -->
        <?php new Home_HeaderPlugin(); ?>
        <!-- /.Header -->
        <div class="templatemo-detail content">

            <div class="about-detail">
                <h1>Aliquam quis arcu eu mi volutpat elementum</h1>
                <img src="images/3-small.jpg" alt="image 3" class="left shadow">
                <p class="justify">Quisque venenatis, augue at dictum placerat, odio felis condimentum augue, a pellentesque velit mi sed justo. Sed tempor tempor massa, vitae auctor lacus ullamcorper ac. Nunc vehicula lectus dolor. Nunc dictum enim purus, scelerisque condimentum nisl tincidunt sit amet.</p>
                <br><p>Vivamus iaculis, lacus nec rutrum posuere, ante massa feugiat lorem, ac luctus lectus lectus quis nisi. Mauris tempus in tellus in rutrum. Nulla semper enim a tincidunt convallis. Ut urna magna, tristique vitae ante sit amet, adipiscing semper diam. Curabitur eget enim vel neque mollis mollis. Aliquam quis venenatis nisi.</p>
                <h3 class="subtitle">Proin adipiscing non urna ut gravida</h3>
                <ul class="checkmark pad-left">
                    <li>Etiam consequat varius arcu eu interdum</li>
                    <li>Nunc pharetra tortor non neque posuere ultricies</li>
                    <li>Sed sed massa ut lectus egestas vulputate</li>
                    <li>Phasellus sit amet erat quis odio euismod</li>
                </ul>

                <br>

                <h1>Suspendisse quis est et nunc fermentum dictum</h1>
                <img src="images/6-small.jpg" alt="image 6" class="left shadow">
                <p class="justify">Duis pretium metus sit amet quam placerat, nec ullamcorper tortor porta. Integer aliquam, elit porta ullamcorper auctor, dui turpis placerat diam, eu scelerisque nunc risus sed turpis. In id iaculis nunc. Sed fermentum purus orci, id tempus tortor congue nec. Integer non dui aliquam, molestie enim pretium, congue nisl. Proin condimentum quam at massa vehicula iaculis. Duis dictum hendrerit varius. Nulla mi odio, convallis ac molestie non, cursus condimentum tellus. Nam ornare lacus et vulputate rhoncus. Morbi a felis adipiscing, dapibus elit quis, imperdiet lacus.</p>
                <br><p>Curabitur sit amet magna sit amet nisl commodo iaculis. Sed pellentesque mauris id gravida porttitor. Maecenas eros nisl, molestie non nulla in, faucibus porta dui. Proin eu erat vitae mauris ullamcorper luctus quis vel nisi. Morbi pretium et justo at blandit. Morbi quis aliquam ipsum.</p>
            </div>

        </div>
    </div>
    <!-- /.content-container -->
    <!-- footer -->
    <?php new Home_FooterPlugin(); ?>
    <!-- /.footer -->
</div>

<?php $this->begain_script_block(); ?>
<script>
	var HomeAbout = new Home.About();
    HomeAbout.init();
</script>
<?php $this->end_script_block(); ?>