<div class="main-container">
    <?php
        new Home_NavPlugin();
    ?>

    <div class="content-container">
        <?php
        new Home_HeaderPlugin();
        ?>

        <div id="portfolio-content" class="center-text">

            <div class="portfolio-page" id="page-<?=$page['page']?>">
                <? foreach ($photo_info as $value) {?>
                    <div class="portfolio-group">
                        <a class="portfolio-item" href="<?= UrlBuilder::build_static($value['path']); ?>">
                            <img src="<?= UrlBuilder::build_static($value['path']); ?>" alt="image 1">
                            <div class="detail">
                                <h3><?=$value['title']?></h3>
                                <p><?=$value['abs']?></p>
                                <span class="btn">View</span>
                            </div>
                        </a>
                    </div>
                <?}?>
            </div>

             <!-- page 3 -->
            <?php
                new Home_PagesPlugin($pages);
            ?>
<!--            <div class="pagination">-->
<!--                <ul class="nav">-->
<!--                    <li class="active">1</li>-->
<!--                    <li>2</li>-->
<!--                    <li>3</li>-->
<!--                </ul>-->
<!--            </div>-->


        </div>
    </div>	<!-- /.content-container -->

    <?php
        new Home_FooterPlugin();
    ?>
</div>
<?php foreach ($this->get_static_js_list() as $js): ?>
    <script type="text/javascript" src="<?= UrlBuilder::build_static($js); ?>"></script>
<?php endforeach; ?>
<script type="text/javascript" src="<?= $this->build_js_url() ?>"></script>

<script type="text/javascript">
    $(function () {
        $('.pagination li').click(changePage);
        $('.portfolio-item').magnificPopup({
            type: 'image',
            gallery:{
                enabled:true
            }
        });
    });
</script>

<?php $this->begain_script_block(); ?>
<script>
    var index = new Home.Index();
    index.init();
</script>
<?php $this->end_script_block(); ?>