<div class="main-container">
    <!-- nav -->
    <?php new Home_NavPlugin(); ?>
    <!-- /.nav -->
    <!-- content-container -->
    <div class="content-container">
        <!-- Header -->
        <?php new Home_HeaderPlugin(); ?>
        <!-- /.Header -->
        <div id="portfolio-content" class="center-text">

            <div class="portfolio-page" id="page-<?php echo $page['page']?>">
                <?php if ($photo_info){?>
                    <?php foreach ($photo_info as $value) {?>
                        <div class="portfolio-group">
                            <a class="portfolio-item" href="<?php echo UrlBuilder::build_static($value['path']); ?>">
                                <img src="<?php echo UrlBuilder::build_static($value['path']); ?>" alt="<?php echo $value['title']?>">
                                <div class="detail">
                                    <h3><?php echo $value['title']?></h3>
                                    <p><?php echo $value['abs']?></p>
                                    <span class="btn">View</span>
                                </div>
                             </a>
                        </div>
                    <?php }?>
                <?php }else{ ?>
                    <div class="portfolio-group">
                        <a class="portfolio-item" href="#">
                            <img src="#" alt="暂无数据">
                            <div class="detail">
                                <h3>暂无数据</h3>
                                <p>暂无数据</p>
                                <span class="btn">View</span>
                            </div>
                        </a>
                    </div>
                <?php } ?>
            </div>

            <?php
                new Home_PagesPlugin($pages);
            ?>

        </div>
    </div>
    <!-- /.content-container -->
    <!-- footer -->
    <?php new Home_FooterPlugin(); ?>
    <!-- /.footer -->
</div>

<?php foreach ($this->get_static_js_list() as $js): ?>
    <script type="text/javascript" src="<?php echo UrlBuilder::build_static($js); ?>"></script>
<?php endforeach; ?>
<script type="text/javascript">
    $(function () {
        $('.pagination li').click(changePage);
        $('.portfolio-item').magnificPopup({
            type: 'image',
            gallery:{
                enabled:true
            }
        });
    });
</script>

<?php $this->begain_script_block(); ?>
<script>
    var index = new Home.Index();
    index.init();
</script>
<?php $this->end_script_block(); ?>