<div class="main-container">
    <!-- nav -->
    <?php new Home_NavPlugin(); ?>
    <!-- /.nav -->
    <!-- content-container -->
    <div class="content-container">
        <!-- Header -->
        <?php new Home_HeaderPlugin(); ?>
        <!-- /.Header -->
        <div id="templatemo_timeline" class="content">
            <div class="container-fluid">
                <div class="time_line_wap left_timeline">
                    <div class="time_line_paragraph">
                        <div class="time_line_caption left">9 days ago</div>
                        <div class="time_line_icon right"><i class="fa fa-gift"></i></div>
                        <h1>Lorem ipsum dolor sit amet</h1>
                        <p>You can easily change icons by <a rel="nofollow" href="http://fontawesome.info/font-awesome-icon-world-map/">Font Awesome</a>. Example: <strong>&lt;i class=&quot;fa fa-gift&quot;&gt;&lt;/i&gt;</strong> Nulla nec fermentum libero. Duis quis fermentum libero. Nunc facilisis ultrices fringilla. Nullam sed ligula ac libero venenatis pellentesque vitae nec mauris.</p>
                    </div>
                </div>
                <div class="time_line_wap left_timeline">
                    <div class="time_line_paragraph">
                        <div class="time_line_caption left">2 weeks ago</div>
                        <div class="time_line_icon right"><i class="fa fa-heart"></i></div>
                        <h1>Excepteur sint occaecat cupidatat</h1>
                        <p>Vestibulum pellentesque leo mi, non adipiscing odio tristique in. Aliquam suscipit magna nisi, non dapibus purus cursus in. Sed vitae quam bibendum mauris vehicula pretium. Curabitur ac ornare magna. Vestibulum dapibus dolor porttitor urna pretium euismod. Aliquam lobortis enim at lacinia mollis.</p>
                    </div>
                </div>
                <div class="time_line_wap left_timeline">
                    <div class="time_line_paragraph">
                        <div class="time_line_caption left">one month ago</div>
                        <div class="time_line_icon right"><i class="fa fa-chain"></i></div>
                        <h1>Doloremque laudantium</h1>
                        <p>Pellentesque vitae dictum ipsum, sit amet pretium dolor. Nullam at eleifend dolor, ut suscipit erat. Nunc dignissim, libero nec tincidunt lobortis, lectus purus tristique lacus, et consectetur leo libero in erat. Pellentesque ac sapien ut tellus porta malesuada. Nulla eget diam elit. Ut et arcu malesuada, facilisis nisl ut, commodo ligula.</p>
                    </div>
                </div>
                <div class="time_line_wap left_timeline">
                    <div class="time_line_paragraph">
                        <div class="time_line_caption left">18 May 2084</div>
                        <div class="time_line_icon right"><i class="fa fa-tablet"></i></div>
                        <h1>Neque porro quisquam</h1>
                        <p>Ut varius nibh adipiscing sagittis lobortis. Sed imperdiet risus enim, sit amet tempus nisi lobortis a. Etiam in gravida leo, non interdum sapien. Sed mi odio, pharetra at tellus ac, adipiscing pulvinar dolor. Nulla quis suscipit urna. Integer congue non nunc a luctus.</p>
                    </div>
                </div>
                <div class="time_line_wap left_timeline">
                    <div class="time_line_paragraph">
                        <div class="time_line_caption left">20 April 2084</div>
                        <div class="time_line_icon right"><i class="fa fa-thumbs-o-up"></i></div>
                        <h1>Sed do eiusmod tempor</h1>
                        <p>Maecenas in ipsum pulvinar, dapibus leo ut, adipiscing neque. Phasellus tincidunt arcu eleifend placerat posuere. Nullam nec eros in leo facilisis blandit id in neque. Proin varius, neque in eleifend porta, neque arcu dapibus risus, vel congue ante nibh varius nisi.</p>
                    </div>
                </div>
                <div class="time_line_wap left_timeline">
                    <div class="time_line_paragraph">
                        <div class="time_line_caption left">12 April 2084</div>
                        <div class="time_line_icon right"><i class="fa fa-gavel"></i></div>
                        <h1>Ut enim ad minim veniam</h1>
                        <p>Cras dignissim dui laoreet tellus mattis posuere. Aenean varius ligula sed nisi consectetur, non faucibus sem consequat. Phasellus dignissim venenatis dolor, sit amet molestie nisl tempor vel. Proin blandit, nisi sit amet pretium adipiscing, nisi lorem rhoncus est, in laoreet augue justo vitae nulla.
                            <br><br>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse vel sollicitudin eros, vel vulputate leo.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.content-container -->
    <!-- footer -->
    <?php new Home_FooterPlugin(); ?>
    <!-- /.footer -->
</div>
<?php $this->begain_script_block(); ?>
<script>
	var HomeProject = new Home.Project();
    HomeProject.init();
</script>
<?php $this->end_script_block(); ?>