<footer>
    <p>Copyright &copy; 2018 Kirk  <a href="http://debug.cool/" target="_blank">debug.cool</a></p>
    <div class="social right">
        <?php if ($footer_data['friends_link']){?>
            <?php foreach ($footer_data['friends_link'] as $value){?>
                <span><a href="<?php echo $value['url']?>" title="<?php echo $value['abs']?>"><?php echo $value['title']?></a></span>&nbsp;&nbsp;
            <?php }?>
        <?php } else { ?>
            <span><a href="http://debug.cool" title="Kirk">Kirk`s Blog</a></span>&nbsp;&nbsp;
        <?php }?>

    </div>
</footer>