<header>
    <?php if ($header_data['notice']) {?>
        <h1 class="center-text"><?php echo $header_data['notice']['title']?></h1>
        <h2 class="center-text"><?php echo $header_data['notice']['abs']?><?php echo $header_data['notice']['content']?></h2>
    <?php }else{ ?>
        <h1 class="center-text">kirk</h1>
        <h2 class="center-text">A Distributed Framework for PHP</h2>
    <?php }?>

</header>