<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Kirk-Huang</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <?php foreach($left_menu_data as $value){?>
                    <?php if ($value['have_child']){?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo $value['menu_name']; ?> <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <?php foreach ($value['child_menu'] as $child_menu){?>
                                    <li><a href="<?php echo $child_menu['menu_url'];?>"> <?php echo $child_menu['menu_name']; ?></a></li>
                                <?php }?>
                            </ul>
                        </li>
                    <?php }else{?>
                        <li><a href="<?php echo $value['menu_url']; ?>" > <?php echo $value['menu_name']; ?> <span class="sr-only">(current)</span></a></li>
                    <?php } ?>
                <?php }?>
            </ul>

            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <?php foreach ($right_menu_data as $value){?>
                    <?php if ($value['have_child']){?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo $value['menu_name']; ?> <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <?php foreach ($value['child_menu'] as $child_menu){?>
                                <li><a href="<?php echo $child_menu['menu_url']; ?>"><?php echo $child_menu['menu_name'];?></a></li>
                                <?php }?>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                            </ul>
                        </li>
                    <?php }else{?>
                        <li> <a href="<?php echo $value['menu_url']; ?>" > <?php echo $value['menu_name']; ?> </a></li>
                    <?php }?>
                <?php }?>


            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>