<nav class="main-nav">
    <div id="logo" class="left"><a href="#">Kirk Huang</a></div>
    <ul class="nav right center-text">
        <?php if ($nav_data['menu']){?>
            <?php foreach ($nav_data['menu'] as $value){?>
                <li class="btn<?php echo $nav_data['page_dot'] == $value["ename"] ? " active" : ""?>">
                    <?php if ($nav_data['page_dot'] == $value["ename"]){?>
                        <?php echo $value["name"]?>
                    <?php }else{ ?>
                        <a href="<?php echo $value["url"]?>"><?php echo $value["name"]?></a>
                    <?php } ?>
                </li>
            <?php }?>
        <?php }else{ ?>
            <li class="btn active">
                <a href="/">主页</a>
            </li>
        <?php }?>

    </ul>
</nav>