<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Blank</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->

<?php $this->begain_script_block(); ?>
<script>
	var AdminDemoBlank = new Admin.Demo.Blank();
    AdminDemoBlank.init();
</script>
<?php $this->end_script_block(); ?>