<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8">
    <title><?=$this->get_title()?></title>
    <meta name="renderer" content="webkit">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" rev="stylesheet" href="<?=$this->build_css_url()?>" type="text/css" />
    <link rel="shortcut icon" href="<?=UrlBuilder::build_static('images/icon.png')?>" />
</head>
<body>
<?php
$called_class = get_called_class();
//new Admin_HeaderPlugin(array('name'=>$called_class::get_name()));
?>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span2">

            <?php
            $called_class = get_called_class();
//            new Admin_NavPlugin(array('list'=>$called_class::get_nav_list(),'nav_name'=>$this->get_nav_name()));
            ?>
        </div><!--/span-->
        <div class="span10">
            <div class="well">
                <?php
                $this->build_content();
                ?>
            </div>
        </div><!--/span-->

    </div><!--/row-->
    <hr>
<!--    --><?php
//    new Admin_FooterPlugin();
//    ?>

</div><!--/.fluid-container-->
<?php foreach($this->get_static_js_list() as $js):?>
    <script type="text/javascript" src="<?=UrlBuilder::build_static($js); ?>"></script>
<?php endforeach;?>

<script type="text/javascript" src="<?=$this->build_js_url()?>"></script>
<script>
    var adminFrame = new Admin.Frame();
</script>
<?php $this->write_script_blocks(); ?>
</body>
</html>
