<!DOCTYPE html>
<head>
    <title><?php echo $this->get_title() ?></title>

    <?php if ($this->get_keywords()) : ?>
        <meta name="Keywords" content="<?php echo $this->get_keywords() ?>"/>
    <?php endif; ?>

    <?php if ($this->get_description()) : ?>
    <meta name="Description" content="<?php echo $this->get_description() ?>"/>
    <?php endif; ?>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <?php foreach ($this->get_static_css_list() as $css): ?>
    <link rel="stylesheet" rev="stylesheet" href="<?php echo UrlBuilder::build_static($css); ?>" type="text/css"/>
    <?php endforeach; ?>

</head>
<body> 

<?php
    $this->build_content();
?>

<?php $this->write_script_blocks(); ?>

</body>
</html>