<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title><?= $this->get_title() ?></title>

    <?php if ($this->get_keywords()) : ?>
        <meta name="Keywords" content="<?= $this->get_keywords() ?>"/>
    <?php endif; ?>

    <?php if ($this->get_description()) : ?>
        <meta name="Description" content="<?= $this->get_description() ?>"/>
    <?php endif; ?>

    <link rel="stylesheet" rev="stylesheet" href="<?= $this->build_css_url() ?>" type="text/css"/>

    <?php foreach ($this->get_static_css_list() as $css): ?>
        <link rel="stylesheet" rev="stylesheet" href="<?= UrlBuilder::build_static($css); ?>" type="text/css"/>
    <?php endforeach; ?>

    <?php foreach ($this->get_static_js_list() as $js): ?>
        <script type="text/javascript" src="<?= UrlBuilder::build_static($js); ?>"></script>
    <?php endforeach; ?>
</head>

<body>

<?php
    $this->build_content();
?>

<?php foreach ($this->get_static_js_list() as $js): ?>
    <script type="text/javascript" src="<?= UrlBuilder::build_static($js); ?>"></script>
<?php endforeach; ?>

<script type="text/javascript" src="<?= $this->build_js_url() ?>"></script>

<script>
    var homeFrame = new HomeFrame();
    homeFrame.init();
</script>
<?php $this->write_script_blocks(); ?>
</body>
</html>