<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">

            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                </div>
                <!-- /input-group 搜索-->
            </li>

            <li>
                <a href="javascript:;" class="admin-dashboard"><i class="fa fa-dashboard fa-fw"></i> Dashboard </a>
            </li>

            <li>
                <a href="#"><i class="fa fa-bug fa-fw"></i> Spider Manage <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li><a href="javascript:;" class="spider-manage-total">Total Spider</a></li>
                    <li><a href="javascript:;" class="spider-manage-catch">Catch Spider</a></li>
                </ul>
                <!-- /.nav-second-level -->
            </li>

            <li>
                <a href="#"><i class="fa fa-linux fa-fw"></i> System Manage <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li><a href="javascript:;" class="system-manage-vps"> VPS </a></li>
                    <li><a href="javascript:;" class="systme-manage-site"> Site </a></li>
                </ul>
                <!-- /.nav-second-level -->
            </li>

            <li>
                <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Data Analysis <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li><a href="javascript:;" class="analysis-demo"> Demo </a></li>
                    <li>
                        <a href="#shares-details"> Shares Details <span class="fa arrow"></span></a>
                        <ul class="nav nav-third-level">
                            <li><a href="javascript:;" class="shares-detail-hs">沪深</a></li>
                            <li><a href="javascript:;" class="shares-detail-hk">港股</a></li>
                            <li><a href="javascript:;" class="shares-detail-us">美股</a></li>
                            <li><a href="javascript:;" class="shares-detail-coins">基金</a></li>
                            <li><a href="javascript:;" class="shares-detail-person">私募</a></li>
                        </ul>
                        <!-- /.nav-third-level -->
                    </li>

                </ul>
                <!-- /.nav-second-level -->
            </li>



        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->