<!--遮罩层 调用弹窗必须要开启 Start-->
<div class="add-spider-pop-mask" ></div>
<!--遮罩层 调用弹窗必须要开启 End-->

<!--弹窗div 添加爬虫 start-->
<div class="add-spider-point">
    <div class="add-spider-pop">
        <div class="form-box-title">
            <label>添加爬虫</label>
        </div>
        <div class="form-box">
            <label>爬虫名称: </label>
            <input class="form-input" placeholder="请输入爬虫名称" value="" name="spiderName">
        </div>

        <div class="form-box">
            <label>启动命令: </label>
            <input class="form-input" placeholder="请输入爬虫启动命令" value="" name="cmdStart">
        </div>

        <div class="form-box">
            <label>停止命令: </label>
            <input class="form-input" placeholder="请输入爬虫中止命令" value="" name="cmdStop">
        </div>

        <div class="form-btn">
            <input class="normal-btn success" type="button" value="确 认">
            <input class="normal-btn cancel" type="button" value="取 消">
        </div>

    </div>
</div>
<!--弹窗div 添加爬虫 end-->

